apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: image-updater
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Image Updater Project
  sourceRepos:
    - "*"
  destinations:
    - server: https://kubernetes.default.svc
      name: in-cluster
      namespace: argocd
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
