---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-python-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: demo-python-app Cluster Project
  sourceRepos:
    - "*"
  destinations:
    - server: https://kubernetes.default.svc
      name: in-cluster
      namespace: demo-python-app
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
